jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing.key: MyKey
  authorities.key: roles
  header.string: Authorization
  secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

spring:
  application.name: wheelshare
  rsocket:
    server:
      port: 8080
  cassandra:
    contact-points: 127.0.0.1
    port: 9043
    keyspace-name: wheelshare
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  error:
    include-message: always
